// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using NMeCab;
using NMeCab.Alissa;
using JapaneseStyleChanger;

namespace JapaneseStyleChangerTest
{
    [TestClass]
    public class SpacingAndWidthsCases : BaseClass
    {
		// Generated text cases.

        [TestMethod]
        public void Test_SW_MS0000()
        {
			var result = Rewrite("私たちが日常使用していることばは、一定のきまりにしたがって表現されています。", CombineMode.MS);
			Assert.AreEqual("私たちが日常使用していることばは、一定のきまりにしたがって表現されています。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_CG0000()
        {
			var result = Rewrite("私たちが日常使用していることばは、一定のきまりにしたがって表現されています。", CombineMode.CG);
			Assert.AreEqual("私たちが日常使用していることばは、一定のきまりにしたがって表現されています。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_MS0001()
        {
			var result = Rewrite("CoxとBekkerの報告によれば、ピアレビューシステムの重要性が高まっているという。", CombineMode.MS);
			Assert.AreEqual("Cox と Bekker の報告によれば、ピア レビュー システムの重要性が高まっているという。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_CG0001()
        {
			var result = Rewrite("CoxとBekkerの報告によれば、ピアレビューシステムの重要性が高まっているという。", CombineMode.CG);
			Assert.AreEqual("CoxとBekkerの報告によれば、ピアレビューシステムの重要性が高まっているという。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_MS0002()
        {
			var result = Rewrite("Cox と Bekker の報告によれば、ピア レビュー システムの重要性が高まっているという。", CombineMode.MS);
			Assert.AreEqual("Cox と Bekker の報告によれば、ピア レビュー システムの重要性が高まっているという。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_CG0002()
        {
			var result = Rewrite("Cox と Bekker の報告によれば、ピア レビュー システムの重要性が高まっているという。", CombineMode.CG);
			Assert.AreEqual("CoxとBekkerの報告によれば、ピアレビューシステムの重要性が高まっているという。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_MS0003()
        {
			var result = Rewrite("githubにも wikiとか issueとか、直接レポジトリーに関係しない機能がありますが、レポジトリー以外の機能が猛烈にたくさんあるんです。", CombineMode.MS);
			Assert.AreEqual("github にも wiki とか issue とか、直接レポジトリーに関係しない機能がありますが、レポジトリー以外の機能が猛烈にたくさんあるんです。", result, "Unexpected combined text.");
        }
        [TestMethod]
        public void Test_SW_CG0003()
        {
			var result = Rewrite("githubにも wikiとか issueとか、直接レポジトリーに関係しない機能がありますが、レポジトリー以外の機能が猛烈にたくさんあるんです。", CombineMode.CG);
			Assert.AreEqual("githubにもwikiとかissueとか、直接レポジトリーに関係しない機能がありますが、レポジトリー以外の機能が猛烈にたくさんあるんです。", result, "Unexpected combined text.");
        }

		// Postamble

		[ClassInitialize]
		public new static void ClassInitialize(TestContext context)
        {
			BaseClass.ClassInitialize(context);
        }

		[ClassCleanup]
        public new static void ClassCleanup()
        {
			BaseClass.ClassCleanup();
		}

		static string Rewrite(string source, CombineMode mode)
		{
			var analysis = Tagger.Parse(source);
			Combiner.CombineMode = mode;
            var jotai = Combiner.Combine(analysis);
            return jotai;
		}
	}
}
