// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>

using System;
using System.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using NMeCab;
using NMeCab.Alissa;
using JapaneseStyleChanger;

namespace JapaneseStyleChangerTest
{
    [TestClass]
    public class TextPairCases
    {
		// Generated text cases.

        [TestMethod]
        public void Test_JT_0000_書きます()
        {
			var result = ConvertText("書きます");
			Assert.AreEqual("書く", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0001_見ます()
        {
			var result = ConvertText("見ます");
			Assert.AreEqual("見る", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0002_食べます()
        {
			var result = ConvertText("食べます");
			Assert.AreEqual("食べる", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0003_読みます()
        {
			var result = ConvertText("読みます");
			Assert.AreEqual("読む", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0004_貼ります()
        {
			var result = ConvertText("貼ります");
			Assert.AreEqual("貼る", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0005_書きましょう()
        {
			var result = ConvertText("書きましょう");
			Assert.AreEqual("書こう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0006_見ましょう()
        {
			var result = ConvertText("見ましょう");
			Assert.AreEqual("見よう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0007_食べましょう()
        {
			var result = ConvertText("食べましょう");
			Assert.AreEqual("食べよう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0008_読みましょう()
        {
			var result = ConvertText("読みましょう");
			Assert.AreEqual("読もう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0009_貼りましょう()
        {
			var result = ConvertText("貼りましょう");
			Assert.AreEqual("貼ろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0010_書きません()
        {
			var result = ConvertText("書きません");
			Assert.AreEqual("書かない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0011_見ません()
        {
			var result = ConvertText("見ません");
			Assert.AreEqual("見ない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0012_食べません()
        {
			var result = ConvertText("食べません");
			Assert.AreEqual("食べない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0013_読みません()
        {
			var result = ConvertText("読みません");
			Assert.AreEqual("読まない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0014_貼りません()
        {
			var result = ConvertText("貼りません");
			Assert.AreEqual("貼らない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0015_ありません()
        {
			var result = ConvertText("ありません");
			Assert.AreEqual("ない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0016_ありませんでした()
        {
			var result = ConvertText("ありませんでした");
			Assert.AreEqual("なかった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0017_読みませんでした()
        {
			var result = ConvertText("読みませんでした");
			Assert.AreEqual("読まなかった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0018_読めませんでした()
        {
			var result = ConvertText("読めませんでした");
			Assert.AreEqual("読めなかった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0019_読ませませんでした()
        {
			var result = ConvertText("読ませませんでした");
			Assert.AreEqual("読ませなかった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0020_どうでしょうか()
        {
			var result = ConvertText("どうでしょうか");
			Assert.AreEqual("どうだろうか", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0021_欲しいです()
        {
			var result = ConvertText("欲しいです");
			Assert.AreEqual("欲しい", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0022_欲しかったです()
        {
			var result = ConvertText("欲しかったです");
			Assert.AreEqual("欲しかった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0023_欲しそうです()
        {
			var result = ConvertText("欲しそうです");
			Assert.AreEqual("欲しそうだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0024_欲しくありません()
        {
			var result = ConvertText("欲しくありません");
			Assert.AreEqual("欲しくない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0025_欲しくないです()
        {
			var result = ConvertText("欲しくないです");
			Assert.AreEqual("欲しくない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0026_読みたいです()
        {
			var result = ConvertText("読みたいです");
			Assert.AreEqual("読みたい", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0027_好きです()
        {
			var result = ConvertText("好きです");
			Assert.AreEqual("好きだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0028_好きでした()
        {
			var result = ConvertText("好きでした");
			Assert.AreEqual("好きだった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0029_好きでしょう()
        {
			var result = ConvertText("好きでしょう");
			Assert.AreEqual("好きだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0030_終わりましたら()
        {
			var result = ConvertText("終わりましたら");
			Assert.AreEqual("終わったら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0031_書きましたら()
        {
			var result = ConvertText("書きましたら");
			Assert.AreEqual("書いたら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0032_見ましたら()
        {
			var result = ConvertText("見ましたら");
			Assert.AreEqual("見たら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0033_食べましたら()
        {
			var result = ConvertText("食べましたら");
			Assert.AreEqual("食べたら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0034_読みましたら()
        {
			var result = ConvertText("読みましたら");
			Assert.AreEqual("読んだら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0035_貼りましたら()
        {
			var result = ConvertText("貼りましたら");
			Assert.AreEqual("貼ったら", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0036_見てあげます()
        {
			var result = ConvertText("見てあげます");
			Assert.AreEqual("見てあげる", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0037_見てあげてるんです()
        {
			var result = ConvertText("見てあげてるんです");
			Assert.AreEqual("見てあげてるんだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0038_本です()
        {
			var result = ConvertText("本です");
			Assert.AreEqual("本だ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0039_本でしょう()
        {
			var result = ConvertText("本でしょう");
			Assert.AreEqual("本だろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0040_本でした()
        {
			var result = ConvertText("本でした");
			Assert.AreEqual("本だった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0041_僕のです()
        {
			var result = ConvertText("僕のです");
			Assert.AreEqual("僕のだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0042_僕のでしょう()
        {
			var result = ConvertText("僕のでしょう");
			Assert.AreEqual("僕のだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0043_僕のでした()
        {
			var result = ConvertText("僕のでした");
			Assert.AreEqual("僕のだった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0044_静かです()
        {
			var result = ConvertText("静かです");
			Assert.AreEqual("静かだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0045_静かでしょう()
        {
			var result = ConvertText("静かでしょう");
			Assert.AreEqual("静かだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0046_静かでした()
        {
			var result = ConvertText("静かでした");
			Assert.AreEqual("静かだった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0047_読みそうです()
        {
			var result = ConvertText("読みそうです");
			Assert.AreEqual("読みそうだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0048_読みそうでしょう()
        {
			var result = ConvertText("読みそうでしょう");
			Assert.AreEqual("読みそうだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0049_読みそうでした()
        {
			var result = ConvertText("読みそうでした");
			Assert.AreEqual("読みそうだった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0050_来るようです()
        {
			var result = ConvertText("来るようです");
			Assert.AreEqual("来るようだ", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0051_来るようでしょう()
        {
			var result = ConvertText("来るようでしょう");
			Assert.AreEqual("来るようだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0052_来るようでした()
        {
			var result = ConvertText("来るようでした");
			Assert.AreEqual("来るようだった", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0053_美しいでしょう()
        {
			var result = ConvertText("美しいでしょう");
			Assert.AreEqual("美しいだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0054_雨が降るでしょう()
        {
			var result = ConvertText("雨が降るでしょう");
			Assert.AreEqual("雨が降るだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0055_寒いでしょう()
        {
			var result = ConvertText("寒いでしょう");
			Assert.AreEqual("寒いだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0056_困らせるでしょう()
        {
			var result = ConvertText("困らせるでしょう");
			Assert.AreEqual("困らせるだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0057_行うでしょう()
        {
			var result = ConvertText("行うでしょう");
			Assert.AreEqual("行うだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0058_行かないです()
        {
			var result = ConvertText("行かないです");
			Assert.AreEqual("行かない", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0059_行きたいです()
        {
			var result = ConvertText("行きたいです");
			Assert.AreEqual("行きたい", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0060_行くらしいです()
        {
			var result = ConvertText("行くらしいです");
			Assert.AreEqual("行くらしい", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0061_行かないでしょう()
        {
			var result = ConvertText("行かないでしょう");
			Assert.AreEqual("行かないだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0062_行きたいでしょう()
        {
			var result = ConvertText("行きたいでしょう");
			Assert.AreEqual("行きたいだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0063_行くらしいでしょう()
        {
			var result = ConvertText("行くらしいでしょう");
			Assert.AreEqual("行くらしいだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0064_冬らしいでしょう()
        {
			var result = ConvertText("冬らしいでしょう");
			Assert.AreEqual("冬らしいだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0065_書くでしょう()
        {
			var result = ConvertText("書くでしょう");
			Assert.AreEqual("書くだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0066_見るでしょう()
        {
			var result = ConvertText("見るでしょう");
			Assert.AreEqual("見るだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0067_食べるでしょう()
        {
			var result = ConvertText("食べるでしょう");
			Assert.AreEqual("食べるだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0068_読むでしょう()
        {
			var result = ConvertText("読むでしょう");
			Assert.AreEqual("読むだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0069_貼るでしょう()
        {
			var result = ConvertText("貼るでしょう");
			Assert.AreEqual("貼るだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0070_書いたでしょう()
        {
			var result = ConvertText("書いたでしょう");
			Assert.AreEqual("書いただろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0071_見たでしょう()
        {
			var result = ConvertText("見たでしょう");
			Assert.AreEqual("見ただろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0072_食べたでしょう()
        {
			var result = ConvertText("食べたでしょう");
			Assert.AreEqual("食べただろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0073_読んだでしょう()
        {
			var result = ConvertText("読んだでしょう");
			Assert.AreEqual("読んだだろう", result, "Unexpected jotai text.");
        }
        [TestMethod]
        public void Test_JT_0074_貼ったでしょう()
        {
			var result = ConvertText("貼ったでしょう");
			Assert.AreEqual("貼っただろう", result, "Unexpected jotai text.");
        }

		// Postamble

		private static TextStyleChanger Changer;

        [ClassInitialize]
        public static void ClassInitialize(TestContext context)
        {
			Changer = new TextStyleChanger
			{
				ChangeToJotai = true,
			};
        }

        [ClassCleanup]
        public static void ClassCleanup()
        {
			Changer.Dispose();
			Changer = null;
        }

        private static string ConvertText(string ketai)
        {
			return Changer.ChangeText(ketai);
        }
    }
}
